Vagrant.configure("2") do |config|
    config.vm.box = "peru/ubuntu-14.04-server-amd64"
  
    config.vm.define "dockerswarm1" do |dockerswarm1|
      dockerswarm1.vm.network "private_network", ip: "192.168.122.10"
      dockerswarm1.vm.synced_folder "./configs", "/configs"
      dockerswarm1.vm.synced_folder ".", "/vagrant", disabled: true
      dockerswarm1.vm.provider "libvirt" do |vb|
        vb.host = "dockerswarm1"
        vb.memory = 4096
        vb.cpus = 4
      end
  
    end
  
     config.vm.define "dockerswarm2" do |dockerswarm2|
        dockerswarm2.vm.network "private_network", ip: "192.168.122.11"
        dockerswarm2.vm.synced_folder "./configs", "/configs"
        dockerswarm2.vm.synced_folder ".", "/vagrant", disabled: true
        dockerswarm2.vm.provider "libvirt" do |vb|
          vb.host = "dockerswarm2"
          vb.memory = 4096
          vb.cpus = 4
        end
  
     end

     config.vm.define "dockerswarm3" do |dockerswarm2|
        dockerswarm3.vm.network "private_network", ip: "192.168.122.12"
        dockerswarm3.vm.synced_folder "./configs", "/configs"
        dockerswarm3.vm.synced_folder ".", "/vagrant", disabled: true
        dockerswarm3.vm.provider "libvirt" do |vb|
          vb.host = "dockerswarm3"
          vb.memory = 4096
          vb.cpus = 4
        end
  
     end

  end
  